In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("assets/worldcities.csv")

In [5]:
df.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629

In [6]:
df.shape

(48059, 11)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48059 entries, 0 to 48058
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        48059 non-null  str
 1   city_ascii  48057 non-null  str
 2   lat         48059 non-null  float64
 3   lng         48059 non-null  float64
 4   country     48059 non-null  str
 5   iso2        48026 non-null  str
 6   iso3        48059 non-null  str
 7   admin_name  47858 non-null  str
 8   capital     15138 non-null  str
 9   population  47808 non-null  float64
 10  id          48059 non-null  int64
dtypes: float64(3), int64(1), str(7)
memory usage: 6.0 MB

In [14]:
df.columns

Index(['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3',
       'admin_name', 'capital', 'population', 'id'],
      dtype='str')

In [15]:
df.describe()

                lat           lng    population            id
count  48059.000000  48059.000000  4.780800e+04  4.805900e+04
mean      25.391265     16.247459  1.078566e+05  1.447192e+09
std       22.982203     70.460025  6.855111e+05  2.611877e+08
min      -54.933300   -179.600000  0.000000e+00  1.004003e+09
25%       12.192750    -44.156400  1.219100e+04  1.250540e+09
50%       30.934700     14.480300  2.091350e+04  1.380337e+09
75%       42.618900     77.080950  4.680850e+04  1.704000e+09
max       81.716600    179.366700  3.778500e+07  1.934976e+09

In [19]:
df[["lat", "lng"]]

           lat       lng
0      35.6870  139.7495
1      -6.1750  106.8275
2      28.6100   77.2300
3      23.1300  113.2600
4      19.0761   72.8775
...        ...       ...
48054  14.7040   43.5990
48055 -25.4745   30.9703
48056 -33.9681   25.5981
48057 -18.9315   27.8070
48058  18.3420  -64.9331

[48059 rows x 2 columns]

In [ ]:
df.loc[df['population'] > 30000000]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.687,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.175,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.610,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604

In [32]:
df.sort_values('population', ascending=False)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629
...,...,...,...,...,...,...,...,...,...,...,...
48054,Al Jabīn,Al Jabin,14.7040,43.5990,Yemen,YE,YEM,Raymah,admin,NaN,1887910100
48055,Nelspruit,Nelspruit,-25.4745,30.9703,South Africa,ZA,ZAF,Mpumalanga,admin,NaN,1710114438
48056,Gqeberha,Gqeberha,-33.9681,25.5981,South Africa,ZA,ZAF,Eastern Cape,NaN,NaN,1710000082
48057,Lupane,Lupane,-18.9315,27.8070,Zimbabwe,ZW,ZWE,Matabeleland North,admin,NaN,1716206606
48058,Charlotte Amalie,Charlotte Amalie,18.3420,-64.9331,U.S. Virgin Islands,VI,VIR,Virgin Islands,primary,NaN,1850037473